import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Laboratório remoto | Quixadá</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.lform}>
        <form action="" className={styles.form}>
          <h1 className={styles.form__title}>Fazer login</h1>

          <div className={styles.form__div}>
            <input type="text" className={styles.form__input} placeholder=" " />
            <label htmlFor="" className={styles.form__label}>Login</label>
          </div>

          <div className={styles.form__div}>
            <input type="password" className={styles.form__input} placeholder=" "/>
            <label htmlFor="" className={styles.form__label}>Password</label>
          </div>

          <input type="submit" className={styles.form__button} value="Entrar"></input>
        </form>
      </div>
    </>
  )
}

export default Home
